quiet: true
download-external-modules: true
skip-check:
  - CKV_GCP_74 # silencing due to the bug for checking private_ip_google_access in vpc module
  - CKV_SECRET_6
  - CKV_TF_1 # Ensure Terraform module sources use a commit hash
  - CKV2_GCP_18  # Ensure GCP network defines a firewall and does not use the default firewall
skip-path:
 - gha-creds-*json
