ignored:
  - DL3008
  - DL3059
  - DL4001
  - DL4006
  - DL3003

# to remove for workshop, pining pip version
# FIXME:remove
override:
  info:
    - DL3013
failure-threshold: warning
# end remove section