tbd_tpcdi:
  target: dev
  outputs:
    dev:
      type: spark
      method: session
      schema: demo
      host: NA                           # not used, but required by `dbt-core`
      server_side_parameters:
        "spark.driver.memory": "2g"
        "spark.executor.memory": "2g"
        "spark.executor.instances": "2"
        "spark.hadoop.hive.metastore.warehouse.dir": "hdfs:///user/hive/warehouse/"