name: Plan / Apply On Merge

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
  # Add "id-token" with the intended permissions.
    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        branches: ['master']
        plugins: [    '@semantic-release/commit-analyzer',
                      '@semantic-release/release-notes-generator',
                      '@semantic-release/github']
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: 'actions/checkout@v3'
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
        service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
    - name: Terraform Apply
      id: plan
      run: terraform apply -no-color -var-file env/project.tfvars -auto-approve
      continue-on-error: false