name: Release/apply
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
  # Add "id-token" with the intended permissions.
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      issues: write

    steps:
    - uses: 'actions/checkout@v3'
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        branch: 'master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
        service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
    - name: Terraform Init
      id: init
      run: terraform init -backend-config=env/backend.tfvars
    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color -var-file env/project.tfvars -auto-approve
      continue-on-error: false