---
name: Tech Tests

# Controls when the workflow will run
on: [pull_request]
jobs:
  iac_checks:
    runs-on: ubuntu-latest
  # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: write

    steps:
    - uses: 'actions/checkout@v3'
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        recursive: true
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
        service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: false

    - name: Terraform Init
      id: init
      run: terraform init -backend-config=env/backend.tfvars

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -var-file env/project.tfvars
      continue-on-error: false


